service: ${env:MODEL_NAME}

plugins:
  - serverless-plugin-log-retention
custom:
  model_name: ${env:MODEL_NAME}
  ecr_image: ${env:aws_account_id}.dkr.ecr.${self:provider.region}.amazonaws.com/embedding-${self:custom.model_name}:latest
provider:
  name: aws # provider
  region: us-east-1 # aws region
  memorySize: 3008 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  environment:
    TRANSFORMERS_CACHE: /var/task
  apiGateway:
    apiKeys:
      - ${self:custom.model_name}-apikey


functions:
  sentence-encoding:
    image: ${self:custom.ecr_image}
    logRetentionInDays: 1
   
    events:
      - http:
          path: embedding # http path
          method: post # http method
          private: true
      - schedule:
          name: ${self:custom.model_name}-warm
          rate: rate(5 minutes)